### PR TITLE
Pass through all docs and make consistant (and correct minor issues)

### LINKED ISSUE #25: Fix `find` docs example
Looking over a recent fix for these docs, I realized that the example is actually incorrect. The `find` property creator returns a getter, so the example should _not_ be `.getHeader()`, but `.header` instead.

### PR DESCRIPTION
**Pull request by Robdel12**
## What is this?

With #51 being merged through it was a good time to go through and make all of our inline docs consistent in style. With a fresh pair of eyes I went through all of the docs and double checked everything. It's possible I missed things, so please double check! 

This will close #25

### CODE REVIEW

File: src/interactions/find-all.js [hunk 1]
```diff
@@ -25,12 +25,12 @@ export function findAll(selector) {
...
  * ``` javascript
  * \@interactor class ListInteractor {
- *   getItems = findAll('li')
+ *   items = findAll('li');
  * }
  * ```
  *
  * ``` javascript
- * let $listItems = await new ListInteractor('ul').getItems()
+ * let $listItems = await new ListInteractor('ul').items;
```
Comment (wwilsman) [inline src/interactions/find-all.js]: No need to `await` here

File: src/interactions/find.js [hunk 2]
```diff
@@ -23,12 +23,12 @@ export function find(selector) {
...
  * ``` javascript
  * \@interactor class PageInteractor {
- *   getHeading = find('h1.heading')
+ *   heading = find('h1.heading');
  * }
  * ```
  *
  * ``` javascript
- * let $heading = await new PageInteractor().getHeading()
+ * let $heading = await new PageInteractor().heading;
```
Comment (wwilsman) [inline src/interactions/find.js]: No need to `await` here either

File: src/interactions/find-all.js [hunk 3]
```diff
@@ -6,7 +6,7 @@ import { computed } from './helpers';
  * matching the provided selector.
  *
  * ``` javascript
- * let $listItems = await new Interactor('ul').findAll('li');
+ * let $listItems = new Interactor('ul').findAll('li');
```
Comment (wwilsman) [inline src/interactions/find-all.js]: The methods `find` and `findAll` still needs to `await`. The property creators do not. You can see in the two function bodies for each one returns a convergence and the other returns a computed element.

The methods are used to wait for elements to exist, and the created properties can be used inside convergent assertions.
