### PR TITLE
Change how interactors handle nested relationships

### LINKED ISSUE #9: Complex nested interactor functions do not work as expected
Given these interactors:

```js
@interactor class SignInInteractor {
  fillName = fillable('[data-test-name-input]')
  fillEmail = fillable('[data-test-email-input]')
  submit = clickable('[data-test-submit]')
  fillAndSubmit(name, email) {
    return this
      .fillName(name)
      .fillEmail(email)
      .submit()
  }
}

@interactor class PageInteractor {
  signInForm = new SignInInteractor('[data-test-signin-form]')
}
```

I would expect this to work:

```js
new PageInteractor()
  .signInForm.fillAndSubmit('Wil', 'wil@frontside.io')
```

But instead, an error is throw that might look like this:

```
PageInteractor.fillEmail is not a function
```

This is because when an interactor is nested, it's methods return new instances of the parent interactor. So `fillName()` in `SignInInteractor` will return a new `PageInteractor`.

We should have a way to break out of this nested structure for complex methods such as this. Something like `this.pure()`, `this.scoped()`, or something akin to return an un-nested interactor.

### PR DESCRIPTION
**Pull request by wwilsman**
## Purpose

Fixes #9. Previously, when a parent was provided and a new instance was created from an existing instance, the constructor returned a new instance of the parent. This caused issues with complex interaction methods that reference other methods of the current interactor.

For example:

```js
@interactor class ChildInteractor {
  someAction = action(...);
  complexAction() {
    return this
      .click(...)
      .someAction(...)
  }
}

@interactor class ParentInteractor {
  child = new ChildInteractor()
}
```

Using the example above, `new ParentInteractor().child.complexAction()` will throw an error because `click(...)` returns an instance of `PageInteractor` which does not specify `someAction`.

## Approach

Instead of returning a parent instance in the constructor after a new instance is created, when `parent` is provided to an interactor the methods are wrapped to return parent instances _after_ they have been called.

Doing it this way is no different than:

```js
new PageInteractor()
  .append(new CustomInteractor().complexAction())
```

But it is done for us automatically when providing a `parent` option.

### CODE REVIEW

File: src/interactor.js [hunk 1]
```diff
@@ -180,6 +184,9 @@ export default class Interactor extends Convergence {
     return $$(selector, this.$root);
   }
 
+  chain(parent) {
```
Comment (Robdel12) [inline src/interactor.js]: What's this for?

File: src/utils.js [hunk 2]
```diff
@@ -95,3 +95,27 @@ export function isPropertyDescriptor(descr) {
...
+    // uses descriptors to avoid invoking getters when filtering
+    descr = Object.assign({}, Object.getOwnPropertyDescriptors(proto), descr);
+    proto = Object.getPrototypeOf(proto);
+  }
+
+  return Object.keys(descr).filter(name => {
+    return name !== 'constructor' &&
+      typeof descr[name].value === 'function';
+  });
+}
```
Comment (Robdel12) [inline src/utils.js]: Are we testing this any other browsers? I'm pretty sure it's fine but we should probably double check?

Comment (wwilsman) [reply src/utils.js]: We're using `@babel/env` which has a polyfill for `getOwnPropertyDescriptors`. I don't see anything else here that might have cross browser issues. But it would be nice to eventually have `@bigtest/interactor` being tested in multiple browsers.

File: src/interactor.js (hunk 1 above)
Comment (wwilsman) [reply src/interactor.js]: Left over from trying to figure out the best way to do this parent stuff. ✂️
